#!/usr/bin/env python3
"""
Cross-platform Arduino library installer for this project.
Auto-generated by the check-dependencies workflow — do not edit manually.

Usage:
  python install_libraries.py
  python install_libraries.py --path /custom/arduino/libraries
"""

import argparse
import os
import platform
import subprocess
import sys
from pathlib import Path

# Libraries to install by name via arduino-cli (or Arduino Library Manager)
NAMED_LIBRARIES = ['OneWire', 'DallasTemperature', 'TinyGPSPlus']

# Libraries to install by cloning from git
URL_LIBRARIES = ['https://github.com/Sensirion/arduino-i2c-scd30.git', 'https://github.com/Sensirion/arduino-core.git', 'https://github.com/RobTillaart/MS5611.git', 'https://github.com/DFRobot/DFRobot_OzoneSensor.git']


def get_arduino_libraries_path():
    """Return the default Arduino libraries path for the current OS."""
    system = platform.system()
    home = Path.home()
    if system == "Windows":
        docs = Path(os.environ.get("USERPROFILE", str(home))) / "Documents"
    elif system == "Darwin":  # macOS
        docs = home / "Documents"
    else:  # Linux
        return home / "Arduino" / "libraries"
    return docs / "Arduino" / "libraries"


def _run(cmd):
    print(f"    $ {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout.strip():
        print(result.stdout.rstrip())
    if result.returncode != 0 and result.stderr.strip():
        print(f"    stderr: {result.stderr.rstrip()}", file=sys.stderr)
    return result.returncode == 0


def _has_arduino_cli():
    try:
        subprocess.run(["arduino-cli", "version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def install_named_libraries(libs_path):
    """Install named libraries via arduino-cli, or print manual instructions."""
    if not NAMED_LIBRARIES:
        return
    print("\nInstalling named libraries...")
    if _has_arduino_cli():
        for name in NAMED_LIBRARIES:
            print(f"  Installing {name} via arduino-cli...")
            _run(["arduino-cli", "lib", "install", name])
    else:
        print("  arduino-cli not found.")
        print("  Please install the following via the Arduino Library Manager:")
        for name in NAMED_LIBRARIES:
            print(f"    - {name}")


def install_url_libraries(libs_path):
    """Clone or update git-based libraries into the Arduino libraries folder."""
    if not URL_LIBRARIES:
        return
    libs_path.mkdir(parents=True, exist_ok=True)
    print(f"\nInstalling URL-based libraries into: {libs_path}")
    for url in URL_LIBRARIES:
        repo_name = url.rstrip("/").split("/")[-1]
        if repo_name.endswith(".git"):
            repo_name = repo_name[:-4]
        dest = libs_path / repo_name
        if dest.exists():
            print(f"  Updating {repo_name}...")
            _run(["git", "-C", str(dest), "pull"])
        else:
            print(f"  Cloning {repo_name} from {url}...")
            _run(["git", "clone", url, str(dest)])


def main():
    parser = argparse.ArgumentParser(
        description="Install Arduino libraries required by this project."
    )
    parser.add_argument(
        "--path",
        type=Path,
        default=None,
        help="Arduino libraries folder (default: auto-detected per OS)",
    )
    args = parser.parse_args()

    libs_path = args.path or get_arduino_libraries_path()
    print(f"Arduino libraries directory: {libs_path}")

    install_named_libraries(libs_path)
    install_url_libraries(libs_path)

    print("\nInstallation complete.")


if __name__ == "__main__":
    main()
