name: Compile Sketches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV
      
      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - src
            - scientificCode
          libraries: |
            - name: SD
            - name: OneWire
            - name: DallasTemperature
            - name: TinyGPSPlus
            - source-url: https://github.com/gronat/MS5611.git
            - source-url: https://github.com/DFRobot/DFRobot_OzoneSensor.git
          enable-deltas-report: true
          cli-compile-flags: |
            - --build-path="./src/build/arduino.avr.uno"

      - name: Compile C to WASM
        run: |
          source $GITHUB_ENV
          emcc chips/gps-neo6m.chip.c -o ./chips/gps-neo6m.chip.wasm -s WASM=1

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: / # directory with wokwi.toml, relative to repo's root
          expect_text: 'Hello, world!' # optional

      # This step is needed to pass the size data to the report job.
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: sketches-reports
          path: sketches-reports

      - uses: arduino/report-size-deltas@v1
        if: github.event_name == 'pull_request'
        with:
          sketches-reports-source: sketches-reports
          github-token: ${{ secrets.SPACE_API_KEY_GITHUB_PR }}

