name: Compile Sketches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "myFile.print"
          replace: "Serial.print"
          include: "**src.ino"
          regex: true
      
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./src/src.ino
      
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
      
      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - src
            - scientificCode
          libraries: |
            - name: SD
            - name: OneWire
            - name: DallasTemperature
            - name: TinyGPSPlus
            - source-url: https://github.com/gronat/MS5611.git
            - source-url: https://github.com/DFRobot/DFRobot_OzoneSensor.git
          enable-deltas-report: true
          cli-compile-flags: |
            - -e

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: / # directory with wokwi.toml, relative to repo's root
          scenario: 'serial.test.yaml' # optional

      # This step is needed to pass the size data to the report job.
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: sketches-reports
          path: sketches-reports

      - uses: arduino/report-size-deltas@v1
        if: github.event_name == 'pull_request'
        with:
          sketches-reports-source: sketches-reports
          github-token: ${{ secrets.SPACE_API_KEY_GITHUB_PR }}

