name: Compile Sketches

on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            - name: SD
            - name: DHT22
            - name: OneWire
            - name: DallasTemperature
          enable-deltas-report: true

      # This step is needed to pass the size data to the report job.
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: sketches-reports
          path: sketches-reports
          
      # This step is needed to get the size data produced by the compile jobs
      - name: Download sketches reports artifacts
        uses: actions/download-artifact@v4
        with:
          # All workflow artifacts will be downloaded to this location.
          path: sketches-reports

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: sketches-reports
          
