name: Compile Sketches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Rebase branch
        run: |
            git config --global user.name 'skolodny'
            git config --global user.email 'skolodny@student.leffellschool.org'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git checkout ${{ github.head_ref }}
            git pull origin ${{ github.head_ref }}

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - src
            - scientificCode
          libraries: |
            - name: SD
            - name: OneWire
            - name: DallasTemperature
            - name: TinyGPSPlus
            - source-url: https://github.com/gronat/MS5611.git
            - source-url: https://github.com/DFRobot/DFRobot_OzoneSensor.git
          enable-deltas-report: true
          cli-compile-flags: |
            - --build-path="./src/build/arduino.avr.uno"

      - name: Check file paths
        run: ls -R
      
      - name: Commit changes
        run: |
            git add sketches-reports/
            git commit -am "Automated report"
            git push origin HEAD:${{ github.head_ref }}

      # This step is needed to pass the size data to the report job.
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: sketches-reports
          path: sketches-reports

      - uses: arduino/report-size-deltas@v1
        if: github.event_name == 'pull_request'
        with:
          sketches-reports-source: sketches-reports
          github-token: ${{ secrets.SPACE_API_KEY_GITHUB_PR }}

