name: Compile Sketches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - src
            - scientificCode
          libraries: |
            - name: SD
            - name: OneWire
            - name: DallasTemperature
            - name: TinyGPSPlus
            - source-url: https://github.com/gronat/MS5611.git
            - source-url: https://github.com/DFRobot/DFRobot_OzoneSensor.git
          enable-deltas-report: true

      - name: Lint sketch
        uses: arduino/arduino-lint-action@v2
        with:
          compliance: strict
          
